### PR TITLE
Bump size default from 5 to 20

### PR DESCRIPTION
**Pull request by bmquinn**
- Sets the default `size` to 20
- Limits source document count to `5` over the Websocket connection

### CODE REVIEW

**Review by kdid — CHANGES_REQUESTED** [review]
@bmquinn - we had decided to raise size but to still only return 5 though so the UI wouldn't have to change. 

Here's the issue: https://github.com/nulib/repodev_planning_and_docs/issues/5178

**Comment by bmquinn** [comment]
@kdid I think this change should probably include a test, this PR or a separate one you think?

**Comment by kdid** [comment]
A test is always welcome, but it doesn't look like we were testing doc counts before so I'm OK with it not being in this PR - your call.

I would like to see all 20 documents in the metrics though so we know the full context of what the LLM reasoned with. I'm fine if they are in the existing field, as long as it's in order. (Or if it's easier to do an additional field I'm fine with that too.)

Screenshot 2024-08-26 at 7 19 58 AM

**Comment by bmquinn** [comment]
Thanks for the suggestion, and I totally agree. I'll work on adding that right away and push a new commit.

**Review by kdid — APPROVED** [review]

**Review by mbklein — APPROVED** [review]

**Pull request merged**
